var us_states = [
    {name:"United States", region:"US", division:"US", abbreviation:"US"},
    {name:"Alabama", region:"South", division:"East South Central", abbreviation:"AL"},
    {name:"Alaska", region:"West", division:"Pacific", abbreviation:"AK"},
    {name:"Arizona", region:"West", division:"Mountain", abbreviation:"AZ"},
    {name:"Arkansas", region:"South", division:"West South Central", abbreviation:"AR"},
    {name:"California", region:"West", division:"Pacific", abbreviation:"CA"},
    {name:"Colorado", region:"West", division:"Mountain", abbreviation:"CO"},
    {name:"Connecticut", region:"Northeast", division:"New England", abbreviation:"CT"},
    {name:"Delaware", region:"South", division:"South Atlantic", abbreviation:"DE"},
    {name:"District of Columbia", region:"South", division:"South Atlantic", abbreviation:"DC"},
    {name:"Florida", region:"South", division:"South Atlantic", abbreviation:"FL"},
    {name:"Georgia", region:"South", division:"South Atlantic", abbreviation:"GA"},
    {name:"Hawaii", region:"West", division:"Pacific", abbreviation:"HI"},
    {name:"Idaho", region:"West", division:"Idaho", abbreviation:"ID"},
    {name:"Illinois", region:"Midwest", division:"East North Central", abbreviation:"IL"},
    {name:"Indiana", region:"Midwest", division:"East North Central", abbreviation:"IN"},
    {name:"Iowa", region:"Midwest", division:"West North Central", abbreviation:"IA"},
    {name:"Kansas", region:"Midwest", division:"West North Central", abbreviation:"KS"},
    {name:"Kentucky", region:"South", division:"East South Central", abbreviation:"KY"},
    {name:"Louisiana", region:"South", division:"West South Central", abbreviation:"LA"},
    {name:"Maine", region:"Northeast", division:"New England", abbreviation:"ME"},
    {name:"Maryland", region:"South", division:"South Atlantic", abbreviation:"MD"},
    {name:"Massachusetts", region:"Northeast", division:"New England", abbreviation:"MA"},
    {name:"Michigan", region:"Midwest", division:"East North Central", abbreviation:"MI"},
    {name:"Minnesota", region:"Midwest", division:"West North Central", abbreviation:"MN"},
    {name:"Mississippi", region:"South", division:"East South Central", abbreviation:"MS"},
    {name:"Missouri", region:"Midwest", division:"West North Central", abbreviation:"MO"},
    {name:"Montana", region:"West", division:"Mountain", abbreviation:"MT"},
    {name:"Nebraska", region:"Midwest", division:"West North Central", abbreviation:"NE"},
    {name:"Nevada", region:"West", division:"Mountain", abbreviation:"NV"},
    {name:"New Hampshire", region:"Northeast", division:"New England", abbreviation:"NH"},
    {name:"New Jersey", region:"Northeast", division:"Mid-Atlantic", abbreviation:"NJ"},
    {name:"New Mexico", region:"West", division:"Mountain", abbreviation:"NM"},
    {name:"New York", region:"Northeast", division:"Mid-Atlantic", abbreviation:"NY"},
    {name:"North Carolina", region:"South", division:"South Atlantic", abbreviation:"NC"},
    {name:"North Dakota", region:"Midwest", division:"West North Central", abbreviation:"ND"},
    {name:"Ohio", region:"Midwest", division:"East North Central", abbreviation:"OH"},
    {name:"Oklahoma", region:"South", division:"West South Central", abbreviation:"OK"},
    {name:"Oregon", region:"West", division:"Pacific", abbreviation:"OR"},
    {name:"Pennsylvania", region:"Northeast", division:"Mid-Atlantic", abbreviation:"PA"},
    {name:"Rhode Island", region:"Northeast", division:"New England", abbreviation:"RI"},
    {name:"South Carolina", region:"South", division:"South Atlantic", abbreviation:"SC"},
    {name:"South Dakota", region:"Midwest", division:"West North Central", abbreviation:"SD"},
    {name:"Tennessee", region:"South", division:"East South Central", abbreviation:"TN"},
    {name:"Texas", region:"South", division:"West South Central", abbreviation:"TX"},
    {name:"Utah", region:"West", division:"Mountain", abbreviation:"UT"},
    {name:"Vermont", region:"Northeast", division:"New England", abbreviation:"VT"},
    {name:"Virginia", region:"South", division:"South Atlantic", abbreviation:"VA"},
    {name:"Washington", region:"West", division:"Pacific", abbreviation:"WA"},
    {name:"West Virginia", region:"South", division:"South Atlantic", abbreviation:"WV"},
    {name:"Wisconsin", region:"Midwest", division:"East North Central", abbreviation:"WI"},
    {name:"Wyoming", region:"West", division:"Mountain", abbreviation:"WY"}];